name: Build pluginmaster.json
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@main
      - name: Regenerate pluginmaster.json
        run: ./build.ps1
      - name: Commit package update
        uses: EndBug/add-and-commit@main
        with:
          add: ./pluginmaster.json
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Regenerate pluginmaster
